repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: debug-statements
        exclude: (debugging\.py)
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
        exclude: (__snapshots__)
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
            mdformat-pyproject,
        ]
        files: (README\.md)
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-myst,
            mdformat-black,
            mdformat-pyproject,
        ]
        files: (docs/.)
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
